spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://sql7.freesqldatabase.com:3306/sql7606947
    username: sql7606947
    password: yhnZzYzHu1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        format_sql: true
jwt:
  token:
    secret: RG9ndWthbiBPemRlbWlyIEF5cm90ZWsgQ2FzZSBTdHVkeSBTZWNyZXQgS2V5